// Generated by CoffeeScript 1.8.0
(function() {
  var partial, _;

  _ = require('underscore');

  partial = function(serialize) {
    return function(value, primitives) {
      var type;
      if (primitives == null) {
        primitives = ['string', 'number'];
      }
      type = typeof value;
      if (_.contains(primitives, type)) {
        return value;
      } else {
        return serialize(value);
      }
    };
  };

  exports.json = {
    stringify: partial(function(value) {
      var _ref;
      if ((_ref = typeof value) === 'list' || _ref === 'object') {
        return JSON.stringify(value);
      } else {
        return value;
      }
    }),
    parse: function(value) {
      return JSON.parse(value);
    }
  };

}).call(this);
