// Generated by CoffeeScript 1.8.0
(function() {
  var chunks, program, unflatten;

  program = require('commander');

  unflatten = require('../index').unflatten;

  program.option('-c, --connector [_]', 'The character on which to split keys.').parse(process.argv);

  chunks = '';

  process.stdin.on('readable', function() {
    var chunk, flatObj, obj, serializedObj;
    chunk = process.stdin.read();
    if (!chunk) {
      return;
    }
    chunks += chunk;
    try {
      flatObj = JSON.parse(chunks);
      obj = unflatten(flatObj, program);
      serializedObj = JSON.stringify(obj);
      console.log(serializedObj);
      return chunks = '';
    } catch (_error) {}
  });

}).call(this);
